version: '3.7'

volumes:
  mysql_volume_production: {}
  sailmysql:
    driver: local
  sailredis:
    driver: local

networks:
  sail:
    driver: bridge

services:
  laravel:
    build:
      context: .
      dockerfile: ./compose/production/Dockerfile
    image: laravel_app_production
    container_name: laravel_app_production
    env_file:
      - ./.envs/.production/.laravel
      - ./.envs/.production/.mysql
    ports:
      - 80:80
      - 443:443
    depends_on:
      - mysql
    networks:
      - sail
    command: /start
  mysql:
    image: 'mysql:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    env_file:
      - ./.envs/.production/.mysql
    volumes:
      - 'sailmysql:/var/lib/mysql'
    networks:
      - sail
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - sail
  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'sailredis:/data'
    networks:
      - sail
